name: deny

on:
  workflow_call:
    inputs:
      rust-toolchain:
        description: "Rust toolchain; same syntax as dtolnay/rust-toolchain"
        default: "nightly"
        required: false
        type: "string"
      deny-flags:
        description: "Additional flags passed to `cargo deny check`"
        default: "--all-features"
        required: false
        type: "string"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    name: cargo deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-toolchain }}
      - uses: taiki-e/install-action@cargo-deny
      - run: cargo deny check all ${{ inputs.deny-flags }}
